name: ${APP_NAME:-slr-membership}-${NODE_ENV:-production}

services:
  slr-membership:
    image: ${GHCR_IMAGE:-ghcr.io/abitul/slr-membership:latest}
    container_name: ${APP_NAME:-slr-membership}-${NODE_ENV:-production}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - AUTH_TRUST_HOST=true
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    networks:
      - shared-network

networks:
  shared-network:
    name: ${DOCKER_NETWORK:-shared-network}
    external: true
